// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps
After deployment, you must confirm the Amazon SNS subscription, enable maintenance mode, and change the administrator password.

=== Confirm Amazon SNS subscription

This Partner Solution configures a subscription to an SNS topic called `NotifyAdminTopic`. During deployment, you specify an email address to receive notifications in the `EmailSubscription` template parameter. After deployment, Amazon SNS sends an email with the subject *AWS Notification - Subscription Confirmation* to the specified address. Choose the *Confirm subscription* link in the email to confirm the subscription.

=== Enable maintenance mode
Enable maintenance mode to avoid false alarms and accidentally invoking Primary Administration Node (PAN) failover.

. Open the https://console.aws.amazon.com/systems-manager/[Systems Manager console^].
. On the top toolbar, choose AWS Region where the Partner Solution is deployed.
. In the left navigation pane, choose *Parameter Store*.
. Choose the *Maintenance* parameter.
. Choose *Edit*.
. On the *Edit parameter page*, for *Value*, enter `ENABLED`.
. Choose *Save changes*.

=== Change the {partner-product-short-name} administrator user password
{partner-product-short-name} 3.2 requires you to reset the administrator user password after initial setup. After deployment, change the administrator user password in the {partner-product-short-name} console. For more information, refer to https://www.cisco.com/c/en/us/td/docs/security/ise/3-2/admin_guide/b_ise_admin_3_2/b_ISE_admin_32_overview.html#concept_7642DD36C0DD424CA423615BF013D0B9[Administrative Access to {partner-product-short-name}^].

NOTE: For AWS deployments, initial user names for Cisco ISE 3.1 and 3.2+ are `admin` and `iseadmin`, respectively.

=== Update the administrator password in the Systems Manager console
AWS CloudFormation does not support defining template parameters as `SecureString` Systems Manager parameter types. After changing the {partner-product-short-name} administrator user password, update the `ADMIN_PASSWORD` parameter in Parameter Store with the new password.

. Open the https://console.aws.amazon.com/systems-manager/[Systems Manager console^].
. On the top toolbar, choose AWS Region where the Partner Solution is deployed.
. In the left navigation pane, choose *Parameter Store*.
. Choose the *ADMIN_PASSWORD* parameter.
. Choose *Edit*.
. On the *Edit parameter page*, for *Value*, enter the {partner-product-short-name} administrator user password.
. Choose *Save changes*.

NOTE: You can also edit the parameter using the AWS Command Line Interface (AWS CLI). For more information, refer to https://docs.aws.amazon.com/cli/latest/reference/ssm/put-parameter.html[Put-parameter].


.. Update the value of the *ADMIN_PASSWORD* parameter to the new password in the Parameter Store, following the same instructions for the _Maintenance_ parameter.
+
TIP: To conform the principle of least privilege, you may create a new {partner-product-short-name} admin user in {partner-product-short-name} administrative web console, assign it to the admin group *ERS_ADMIN*, and replace the values of the SSM parameters *ADMIN_USERNAME* and *ADMIN_PASSWORD* with this new admin user's data.
+
. Enable API Gateway for the secondary ISE node: We need this in order to use Lambda to promote SPAN to primary while PPAN is down. For the detailed instructions, see https://developer.cisco.com/docs/identity-services-engine/latest/#!cisco-ise-api-framework/cisco-ise-api-gateway[{partner-product-short-name} API Gateway^].
. Install the latest patch of the ISE release: In order to get the latest fixes, please update the nodes with the latest patch release. For detailed instructions, see the section Install a New Patch in the corresponding http://cs.co/ise-rn[Release Notes for Cisco Identity Services Engine^].
. Backup {partner-product-short-name} internal CA chains: This step prepares SPAN to take over PPAN to issue and manage certificates in case that SPAN promoted to primary. https://www.cisco.com/c/en/us/td/docs/security/ise/3-1/admin_guide/b_ise_admin_3_1/b_ISE_admin_31_basic_setup.html#task_E04823B79DCD41EABFAD358D882CE7CA[Export {partner-product-short-name} CA Certificates and Keys^] from the primary ISE node. Then, https://www.cisco.com/c/en/us/td/docs/security/ise/3-1/admin_guide/b_ise_admin_3_1/b_ISE_admin_31_basic_setup.html#task_574F728D24F84475A6099F0D9D3B76B1[Import {partner-product-short-name} CA Certificates and Keys^] into the secondary ISE node.
. End Maintenance mode: Update the parameter *Maintenance* to `DISABLED`.

.Maintenance
****
NOTE: In the future, set the parameter *Maintenance* to `ENABLED` in the AWS Systems Manager's Parameter Store for the region before performing any maintenance. Set it back to `DISABLED` after maintenance.
****


== Resources
* http://cs.co/ise-resources[{partner-product-short-name} & NAC Resources^]
* http://cs.co/ise-community[{partner-product-short-name} Community^]
* http://cs.co/ise-webinars[{partner-product-short-name} Webinars^]
* http://cs.co/ise-videos[{partner-product-short-name} YouTube Channel^]
* http://cs.co/ise-licensing[{partner-product-short-name} Licensing Guide^]
* http://cs.co/ise-api[{partner-product-short-name} API SDK^]