// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps
After deployment, you must complete the following steps.

<<Step 1: Confirm Amazon SNS subscription>>.

<<Step 2: Enable maintenance mode>>.

<<Step 3: Change the {partner-product-short-name} admin password>>.

<<Step 4: Update the admin password in the Systems Manager console>>.

<<Step 5: Enable Amazon API Gateway for the secondary Cisco ISE node>>.
<<Step 6: Install the latest ISE release patch>>.

<<Step 7: Backup {partner-product-short-name} internal CA chains>>.

<<Step 8: Disable maintenance mode>>.


=== Step 1: Confirm Amazon SNS subscription
This Partner Solution configures a subscription to an SNS topic called `NotifyAdminTopic`. During deployment, you specify an email address to receive notifications in the `EmailSubscription` template parameter. After deployment, Amazon SNS sends an email with the subject *AWS Notification - Subscription Confirmation* to the specified address. To confirm the subscription, choose *Confirm subscription* in the email.

=== Step 2: Enable maintenance mode
Before continuing with Steps 2–7, enable maintenance mode to avoid false alarms and accidentally invoking PAN failover.

. Open the https://console.aws.amazon.com/systems-manager/[Systems Manager console^].
. On the top toolbar, choose AWS Region where the Partner Solution is deployed.
. In the navigation pane, choose *Parameter Store*.
. Choose the *Maintenance* parameter.
. Choose *Edit*.
. On the *Edit parameter page*, for *Value*, enter `ENABLED`.
. Choose *Save changes*.

NOTE: After completing Steps 2–7, <<Step 8: Disable maintenance mode, disable maintenance mode>>.

=== Step 3: Change the {partner-product-short-name} admin password
{partner-product-short-name} 3.2 requires you to reset the admin password after initial setup. After deployment, change the admin password in the {partner-product-short-name} console. For more information, refer to https://www.cisco.com/c/en/us/td/docs/security/ise/3-2/admin_guide/b_ise_admin_3_2/b_ISE_admin_32_overview.html#concept_7642DD36C0DD424CA423615BF013D0B9[Administrative Access to {partner-product-short-name}^].

NOTE: For AWS deployments, initial user names for Cisco ISE 3.1 and 3.2+ are `admin` and `iseadmin`, respectively.

=== Step 4: Update the admin password in the Systems Manager console
AWS CloudFormation does not support defining template parameters as `SecureString` Systems Manager parameter types. After changing the {partner-product-short-name} admin password, update the `ADMIN_PASSWORD` parameter in Parameter Store with the new password.

. Open the https://console.aws.amazon.com/systems-manager/[Systems Manager console^].
. On the top toolbar, choose AWS Region where the Partner Solution is deployed.
. In the navigation pane, choose *Parameter Store*.
. Choose the *ADMIN_PASSWORD* parameter.
. Choose *Edit*.
. On the *Edit parameter page*, for *Value*, enter the {partner-product-short-name} admin password.
. Choose *Save changes*.

NOTE: You can also edit the parameter using the AWS Command Line Interface (AWS CLI). For more information, refer to https://docs.aws.amazon.com/cli/latest/reference/ssm/put-parameter.html[Put-parameter^].

To conform the principle of least privilege, do the following:

. Create a new {partner-product-short-name} admin in the {partner-product-short-name} consolee
. Assign the new admin to the admin group `ERS_ADMIN`.
. Update the values of the SSM parameters `ADMIN_USERNAME` and `ADMIN_PASSWORD` with the new admin credentials.

=== Step 5: Enable Amazon API Gateway for the secondary Cisco ISE node
To use AWS Lambda for PAN failover, enable API Gateway for the secondary ISE node. For more information, refer to https://developer.cisco.com/docs/identity-services-engine/latest/#!cisco-ise-api-framework/cisco-ise-api-gateway[{partner-product-short-name} API Gateway^].

=== Step 6: Install the latest ISE release patch
Update the Cisco ISE nodes with the latest Cisco ISE patch release. For more information, refer to http://cs.co/ise-rn[Release Notes^].

=== Step 7: Backup {partner-product-short-name} internal CA chains
This step prepares SPAN to take over PPAN to issue and manage certificates in case that SPAN promoted to primary. https://www.cisco.com/c/en/us/td/docs/security/ise/3-1/admin_guide/b_ise_admin_3_1/b_ISE_admin_31_basic_setup.html#task_E04823B79DCD41EABFAD358D882CE7CA[Export {partner-product-short-name} CA Certificates and Keys^] from the primary ISE node. Then, https://www.cisco.com/c/en/us/td/docs/security/ise/3-1/admin_guide/b_ise_admin_3_1/b_ISE_admin_31_basic_setup.html#task_574F728D24F84475A6099F0D9D3B76B1[Import {partner-product-short-name} CA Certificates and Keys^] into the secondary ISE node.

=== Step 8: Disable maintenance mode
After completing Steps 1-7, disable maintenance mode by resetting the `Maintenance` parameter in Systems Manager to `ENABLED`.

Before performing maintenance in the future, ensure that you repeat the instructions in <<Step 2: Enable maintenance mode, Step 2>> to enable maintenance mode. After maintenance, ensure that you reset the `Maintenance` parameter to `DISABLED`.

== Resources
* http://cs.co/ise-resources[{partner-product-short-name} & NAC Resources^]
* http://cs.co/ise-community[Network Access Control Cisco Community^]
* http://cs.co/ise-webinars[Cisco ISE Webinars and Training Videos^]
* http://cs.co/ise-videos[Cisco ISE - Identity Services Engine on YouTube^]
* http://cs.co/ise-licensing[Cisco Identity Services Engine Ordering Guide^]
* http://cs.co/ise-api[Cisco Identity Services Engine API Reference Guide, v1^]